name: Sync With Upstream

on:
  schedule:
    - cron: '*/20 * * * *' # every 20 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      GITHUB_USER_NAME: acm-cicd
      GITHUB_USER_EMAIL: acm-cicd@redhat.com
      GITHUB_TOKEN: ${{ secrets.FF_GITHUB_TOKEN }}
      LOG_DESTINATION: stolostron-engine/tracking-syncer:main

      REPO_TO_TRACK_HIVE:     openshift/hive:stolostron-engine/tracking-openshift-hive
      BRANCHES_TO_TRACK_HIVE: ocm-2.5-mce-2.0:backplane-2.0


      REPO_TO_TRACK_AI_1:     openshift/assisted-image-service:stolostron-engine/tracking-openshift-assisted-image-service
      BRANCHES_TO_TRACK_AI_1: release-ocm-2.6:backplane-2.1 release-ocm-2.5:backplane-2.0

      REPO_TO_TRACK_AI_2:     openshift/assisted-installer:stolostron-engine/tracking-openshift-assisted-installer
      BRANCHES_TO_TRACK_AI_2: release-ocm-2.6:backplane-2.1 release-ocm-2.5:backplane-2.0

      REPO_TO_TRACK_AI_3:     openshift/assisted-installer-agent:stolostron-engine/tracking-openshift-assisted-installer-agent
      BRANCHES_TO_TRACK_AI_3: release-ocm-2.6:backplane-2.1 release-ocm-2.5:backplane-2.0

      REPO_TO_TRACK_AI_4:     openshift/assisted-service:stolostron-engine/tracking-openshift-assisted-service
      BRANCHES_TO_TRACK_AI_4: release-ocm-2.6:backplane-2.1 release-ocm-2.5:backplane-2.0


      REPO_TO_TRACK_HS_1:     openshift/hypershift:stolostron-engine/tracking-openshift-hypershift
      BRANCHES_TO_TRACK_HS_1: release-4.10:backplane-2.0

      REPO_TO_TRACK_HS_2:     openshift/apiserver-network-proxy:stolostron-engine/tracking-openshift-apiserver-network-proxy
      BRANCHES_TO_TRACK_HS_2: master:backplane-2.0

      REPO_TO_TRACK_HS_3:     openshift/aws-encryption-provider:stolostron-engine/tracking-openshift-aws-encryption-provider
      BRANCHES_TO_TRACK_HS_3: backplane-2.0:backplane-2.0

      REPO_TO_TRACK_HS_4:     openshift/cluster-api:stolostron-engine/tracking-openshift-cluster-api
      BRANCHES_TO_TRACK_HS_4: release-1.0:backplane-2.0

      REPO_TO_TRACK_HS_5:     openshift/cluster-api-provider-agent:stolostron-engine/tracking-openshift-cluster-api-provider-agent
      BRANCHES_TO_TRACK_HS_5: master:backplane-2.0

      REPO_TO_TRACK_HS_6:     openshift/cluster-api-provider-aws:stolostron-engine/tracking-openshift-cluster-api-provider-aws
      BRANCHES_TO_TRACK_HS_6: release-1.1:backplane-2.0

      REPO_TO_TRACK_HS_7:     openshift/cluster-api-provider-azure:stolostron-engine/tracking-openshift-cluster-api-provider-azure
      BRANCHES_TO_TRACK_HS_7: release-1.2:backplane-2.0

      REPO_TO_TRACK_HS_8:     openshift/cluster-api-provider-kubevirt:stolostron-engine/tracking-openshift-cluster-api-provider-kubevirt
      BRANCHES_TO_TRACK_HS_8: release-1.0:backplane-2.0


      REPO_TO_TRACK_STO_BLD_TEMP_1:     stolostron/release:stolostron-engine
      BRANCHES_TO_TRACK_STO_BLD_TEMP_1: backplane-2.1 backplane-2.0 master


      REPO_TO_TRACK_STO_BPO_TEMP_1:     stolostron/backplane-operator:stolostron-engine
      BRANCHES_TO_TRACK_STO_BPO_TEMP_1: backplane-2.1 backplane-2.0 main

      REPO_TO_TRACK_STO_BPO_TEMP_2:     stolostron/backplane-must-gather:stolostron-engine/backplane-must-gather
      BRANCHES_TO_TRACK_STO_BPO_TEMP_2: backplane-2.1:backplane-2.1 backplane-2.0:backplane-2.0 main:main


      REPO_TO_TRACK_STO_CLC_TEMP_1:     stolostron/clusterlifecycle-state-metrics:stolostron-engine/clusterlifecycle-state-metrics
      BRANCHES_TO_TRACK_STO_CLC_TEMP_1: backplane-2.1:backplane-2.1 backplane-2.0:backplane-2.0 main:main

      REPO_TO_TRACK_STO_CLC_TEMP_2:     stolostron/clusterclaims-controller:stolostron-engine/clusterclaims-controller
      BRANCHES_TO_TRACK_STO_CLC_TEMP_2: backplane-2.1:backplane-2.1 backplane-2.0:backplane-2.0 main:main

      REPO_TO_TRACK_STO_CLC_TEMP_3:     stolostron/cluster-curator-controller:stolostron-engine/cluster-curator-controller
      BRANCHES_TO_TRACK_STO_CLC_TEMP_3: backplane-2.1:backplane-2.1 backplane-2.0:backplane-2.0 main:main

      REPO_TO_TRACK_STO_CLC_TEMP_4:     stolostron/managedcluster-import-controller:stolostron-engine/managedcluster-import-controller
      BRANCHES_TO_TRACK_STO_CLC_TEMP_4: backplane-2.1:backplane-2.1 backplane-2.0:backplane-2.0 main:main

      REPO_TO_TRACK_STO_CLC_TEMP_5:     stolostron/provider-credential-controller:stolostron-engine/provider-credential-controller
      BRANCHES_TO_TRACK_STO_CLC_TEMP_5: backplane-2.1:backplane-2.1 backplane-2.0:backplane-2.0 main:main


      REPO_TO_TRACK_STO_CON_TEMP_1:     stolostron/console:stolostron-engine/console
      BRANCHES_TO_TRACK_STO_CON_TEMP_1: backplane-2.1:backplane-2.1 backplane-2.0:backplane-2.0 main:main

      REPO_TO_TRACK_STO_DIS_TEMP_1:     stolostron/discovery:stolostron-engine/discovery
      BRANCHES_TO_TRACK_STO_DIS_TEMP_1: backplane-2.1:backplane-2.1 backplane-2.0:backplane-2.0 main:main


      REPO_TO_TRACK_STO_HS_TEMP_1:      stolostron/hypershift-addon-operator:stolostron-engine/hypershift-addon-operator
      BRANCHES_TO_TRACK_STO_HS_TEMP_1:  backplane-2.1:backplane-2.1 backplane-2.0:backplane-2.0 main:main

      REPO_TO_TRACK_STO_HS_TEMP_2:      stolostron/hypershift-deployment-controller:stolostron-engine/hypershift-deployment-controller
      BRANCHES_TO_TRACK_STO_HS_TEMP_2:  backplane-2.1:backplane-2.1 backplane-2.0:backplane-2.0 main:main


      REPO_TO_TRACK_STO_MSA_TEMP_1:     stolostron/managed-serviceaccount:stolostron-engine/managed-serviceaccount
      BRANCHES_TO_TRACK_STO_MSA_TEMP_1: backplane-2.1:backplane-2.1 backplane-2.0:backplane-2.0 main:main

      REPO_TO_TRACK_STO_MSA_TEMP_2:     stolostron/managed-serviceaccount-e2e:stolostron-engine/managed-serviceaccount-e2e
      BRANCHES_TO_TRACK_STO_MSA_TEMP_2: backplane-2.1:backplane-2.1 backplane-2.0:backplane-2.0 main:main


      REPO_TO_TRACK_STO_SF_TEMP_1:      stolostron/placement:stolostron-engine/placement
      BRANCHES_TO_TRACK_STO_SF_TEMP_1:  backplane-2.1:backplane-2.1 backplane-2.0:backplane-2.0 main:main

      REPO_TO_TRACK_STO_SF_TEMP_2:      stolostron/multicloud-operators-foundation:stolostron-engine/multicloud-operators-foundation
      BRANCHES_TO_TRACK_STO_SF_TEMP_2:  backplane-2.0:backplane-2.0 main:main

      REPO_TO_TRACK_STO_SF_TEMP_3:      stolostron/registration:stolostron-engine/registration
      BRANCHES_TO_TRACK_STO_SF_TEMP_3:  backplane-2.0:backplane-2.0 main:main

      REPO_TO_TRACK_STO_SF_TEMP_4:      stolostron/registration-operator:stolostron-engine/registration-operator
      BRANCHES_TO_TRACK_STO_SF_TEMP_4:  backplane-2.0:backplane-2.0 main:main

      REPO_TO_TRACK_STO_SF_TEMP_5:      stolostron/work:stolostron-engine/work
      BRANCHES_TO_TRACK_STO_SF_TEMP_5:  backplane-2.0:backplane-2.0 main:main

    steps:
    - name: Check out sync tools
      uses: actions/checkout@v3
      with:
         token: ${{ env.GITHUB_TOKEN }}
         repository: stolostron/tracking-tools
         path: tools

    - name: Sync with Upstream
      run: |
        ./tools/tools/fast-forward.sh
