name: Sync With Upstream

on:
  schedule:
    - cron: '*/20 * * * *' # every 20 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      GITHUB_USER_NAME: acm-cicd
      GITHUB_USER_EMAIL: acm-cicd@redhat.com
      GITHUB_TOKEN: ${{ secrets.FF_GITHUB_TOKEN }}
      LOG_DESTINATION: stolostron-engine/tracking-syncer:main

      REPO_TO_TRACK_HIVE:     openshift/hive:stolostron-engine/tracking-openshift-hive
      BRANCHES_TO_TRACK_HIVE: ocm-2.5-mce-2.0:backplane-2.0

      REPO_TO_TRACK_AI_1:     openshift/assisted-image-service:stolostron-engine/tracking-openshift-assisted-image-service
      BRANCHES_TO_TRACK_AI_1: release-ocm-2.6:backplane-2.1 release-ocm-2.5:backplane-2.0

      REPO_TO_TRACK_AI_2:     openshift/assisted-installer:stolostron-engine/tracking-openshift-assisted-installer
      BRANCHES_TO_TRACK_AI_2: release-ocm-2.6:backplane-2.1 release-ocm-2.5:backplane-2.0

      REPO_TO_TRACK_AI_3:     openshift/assisted-installer-agent:stolostron-engine/tracking-openshift-assisted-installer-agent
      BRANCHES_TO_TRACK_AI_3: release-ocm-2.6:backplane-2.1 release-ocm-2.5:backplane-2.0

      REPO_TO_TRACK_AI_4:     openshift/assisted-service:stolostron-engine/tracking-openshift-assisted-service
      BRANCHES_TO_TRACK_AI_4: release-ocm-2.6:backplane-2.1 release-ocm-2.5:backplane-2.0

      REPO_TO_TRACK_HS_1:     openshift/hypershift:stolostron-engine/tracking-openshift-hypershift
      BRANCHES_TO_TRACK_HS_1: release-4.10:backplane-2.0

    steps:
    - name: Check out sync tools
      uses: actions/checkout@v3
      with:
         token: ${{ env.GITHUB_TOKEN }}
         repository: stolostron/tracking-tools
         path: tools

    - name: Sync with Upstream
      run: |
        ./tools/tools/fast-forward.sh
