name: Sync With Upstream

on:
  schedule:
    - cron: '*/20 * * * *' # every 20 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      GITHUB_USER_NAME: acm-cicd
      GITHUB_USER_EMAIL: acm-cicd@redhat.com
      GITHUB_TOKEN: ${{ secrets.FF_GITHUB_TOKEN }}
      LOG_DESTINATION: stolostron-engine/tracking-syncer:main

      REPO_TO_TRACK_1: openshift/hypershift:stolostron-engine/tracking-openshift-hypershift
      BRANCHES_TO_TRACK_1: release-4.10:backplane-2.0

    steps:
    - name: Check out sync tools
      uses: actions/checkout@v3
      with:
         token: ${{ env.GITHUB_TOKEN }}
         repository: stolostron/tracking-tools
         path: tools

    - name: Sync with Upstream
      run: |
        ./tools/tools/fast-forward.sh
